### ISSUE TITLE
ROCprofiler API version is  not compatible

### ISSUE THREAD

**Issue by chrirocca** [ROCm/omniperf#380] opened 2024-06-26 00:40 UTC
i am trying to use omniperf 2.0.1 on a new MI300X. For what I understand, rocprofv2 is required to make it work. I have tried different ROCm versions and ubuntu versions to try to solve this issue but I didn't find any information online and I'm not sure how to solve it.

I have also tried to run rocprofv2 by itself, but it gives me the same error. So i think maybe it could be an error in rocprofv2. 

I was wondering if this error ever occurred to someone and how to solve/find a workaround to make it work.

Thank you,

This is the output i have when trying to profile a program.
![Screenshot 2024-06-26 103340](https://github.com/ROCm/omniperf/assets/145739158/af0a1f61-1ded-45fc-8909-e73e6a6b8801)

**Comment by coleramos425** [comment] 2024-06-26 15:53
@chrirocca what version(s) of ROCm are you seeing this issue with?

**Comment by chrirocca** [comment] 2024-06-26 18:48
I tried with both ROCm 6.0.0 and 6.1, with ubuntu 22.04 and 20.04

**Comment by coleramos425** [comment] 2024-06-26 19:08
Without source code your hip-latency app it's hard to say what exactly is happening here, however, this is indeed a rocprofiler issue. If source code is public can you please share a link? I'll try my best to diagnose, but we may need to file a separate ticket for the rocprofiler project.

**Comment by coleramos425** [comment] 2024-07-03 16:52
@chrirocca can you please follow up with your source code? Otherwise, I'll close this ticket and defer you to the rocprofiler issue tracking page:
https://github.com/ROCm/rocprofiler/issues

**Comment by chrirocca** [comment] 2024-07-04 21:57
Sorry for the slow reply, i didn't see the reply before. 
I attach my repository with source code and makefile i am using, could you check if you can reproduce the error?
https://github.com/chrirocca/test
My guess was a problem with linking to rocprof...

**Comment by ppanchad-amd** [comment] 2024-10-04 15:50
Hi @chrirocca. An internal ticket has been created to assist with your issue. Thanks!

**Comment by zichguan-amd** [comment] 2024-10-04 18:34
Hi @chrirocca, I don't have a MI300X at the moment and I was not able to reproduce the problem on MI100. Can you try running omniperf with `-VVV` flag like this: `omniperf profile -VVV -n latency -- ./hip-latency 0 0 0 0`? 
You can also pass the path to rocprofv2 with the `ROCPROF=<path/to/v2/>` environment variable to make sure that it is using the right rocprof.

**Comment by zichguan-amd** [comment] 2024-10-23 18:56
Closing due to inactivity. Feel free to reach out again if the problem persists.

**Closed by zichguan-amd** 2024-10-23 18:56 UTC
Labels: question, Under Investigation
