### ISSUE TITLE
Metric filtering does not work with baseline compare

### ISSUE THREAD

**Issue by JoseSantosAMD** [ROCm/omniperf#300] opened 2024-03-05 20:17 UTC
**Describe the bug**
Metric filtering does not work with baseline compare

**Development Environment:**
 - Linux Distribution:  RHEL8
 - Omniperf Version: Latest 2.x
 - GPU: MI100
 - Custer (if applicable): HPCFund

**To Reproduce**
1. Run omniperf analyze -p tests/workloads/vcopy/MI100/ -p tests/workloads/vcopy/MI200 --block 11
2.  See error numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('float64'), dtype('<U2')) -> None
3.  Also returns error when passing same path

**Screenshots**
![image](https://github.com/AMDResearch/omniperf/assets/87447437/bc0bb59a-299c-4f03-85cf-cf888cc026ab)
![image](https://github.com/AMDResearch/omniperf/assets/87447437/d4e7c710-d7d9-4d3e-8abe-1f3e36cfce84)

**Additional context**

**Comment by coleramos425** [comment] 2024-03-06 22:29
I couldn't reproduce the issue with the commands you attached. I suspect you may have incorrectly pulled - I'll schedule an appointment to review over the phone

**Comment by skyreflectedinmirrors** [comment] 2024-03-20 14:47
I hit the same issue today on:

```
commit 62221383a701f13fac63bdbf54b8fc6fb87ebc5e (HEAD -> 2.x, origin/2.x)
Author: colramos-amd <colramos@amd.com>
Date:   Mon Mar 18 14:28:14 2024 -0500

    Fixing visualization for Compute Pipeline SOL. Need to consider 'Pct of Peak' rather than 'Avg'
    
    Signed-off-by: colramos-amd <colramos@amd.com>
```

will put details in our chat

**Comment by coleramos425** [comment] 2024-03-21 19:16
If I provide the same path twice, error is correctly caught, i.e.
```console
$ omniperf analyze -p workloads/mix/MI200/ -p workloads/mix/MI200/

  ___                  _                  __ 
 / _ \ _ __ ___  _ __ (_)_ __   ___ _ __ / _|
| | | | '_ ` _ \| '_ \| | '_ \ / _ \ '__| |_ 
| |_| | | | | | | | | | | |_) |  __/ |  |  _|
 \___/|_| |_| |_|_| |_|_| .__/ \___|_|  |_|  
                        |_|                  

Analysis mode = cli
ERROR You cannot provide the same path twice.
```
If I provide two different workloads and block filter, data correctly loads, i.e.
```console
$ omniperf analyze -p workloads/mix/MI200/ -p workloads/mix_k_filt/MI200/ -b 11

  ___                  _                  __ 
 / _ \ _ __ ___  _ __ (_)_ __   ___ _ __ / _|
| | | | '_ ` _ \| '_ \| | '_ \ / _ \ '__| |_ 
| |_| | | | | | | | | | | |_) |  __/ |  |  _|
 \___/|_| |_| |_|_| |_|_| .__/ \___|_|  |_|  
                        |_|                  

Analysis mode = cli
[analysis] deriving Omniperf metrics...
...
--------------------------------------------------------------------------------
11. Compute Units - Compute Pipeline
11.1 Speed-of-Light
╒═════════════╤═══════════════════╤═════════╤═══════════════════╤════════════╤════════╤═══════════╤═════════════════╤═══════════════╤════════════════╕
│ Metric_ID   │ Metric            │     Avg │ Avg               │   Abs Diff │ Unit   │      Peak │ Peak            │   Pct of Peak │ Pct of Peak    │
╞═════════════╪═══════════════════╪═════════╪═══════════════════╪════════════╪════════╪═══════════╪═════════════════╪═══════════════╪════════════════╡
│ 11.1.0      │ VALU FLOPs        │ 7497.89 │ 10053.16 (34.08%) │      11.29 │ Gflop  │  22630.40 │ 22630.4 (0.0%)  │         33.13 │ 44.42 (34.08%) │
├─────────────┼───────────────────┼─────────┼───────────────────┼────────────┼────────┼───────────┼─────────────────┼───────────────┼────────────────┤
│ 11.1.1      │ VALU IOPs         │ 2325.84 │ 1132.67 (-51.3%)  │      -5.27 │ Giop   │  22630.40 │ 22630.4 (0.0%)  │         10.28 │ 5.01 (-51.28%) │
├─────────────┼───────────────────┼─────────┼───────────────────┼────────────┼────────┼───────────┼─────────────────┼───────────────┼────────────────┤
│ 11.1.2      │ MFMA FLOPs (BF16) │    0.00 │ 0.0 (0.0%)        │       0.00 │ Gflop  │ 181043.20 │ 181043.2 (0.0%) │          0.00 │ 0.0 (0.0%)     │
├─────────────┼───────────────────┼─────────┼───────────────────┼────────────┼────────┼───────────┼─────────────────┼───────────────┼────────────────┤
│ 11.1.3      │ MFMA FLOPs (F16)  │    0.00 │ 0.0 (0.0%)        │       0.00 │ Gflop  │ 181043.20 │ 181043.2 (0.0%) │          0.00 │ 0.0 (0.0%)     │
├─────────────┼───────────────────┼─────────┼───────────────────┼────────────┼────────┼───────────┼─────────────────┼───────────────┼────────────────┤
│ 11.1.4      │ MFMA FLOPs (F32)  │    0.00 │ 0.0 (0.0%)        │       0.00 │ Gflop  │  45260.80 │ 45260.8 (0.0%)  │          0.00 │ 0.0 (0.0%)     │
├─────────────┼───────────────────┼─────────┼───────────────────┼────────────┼────────┼───────────┼─────────────────┼───────────────┼────────────────┤
│ 11.1.5      │ MFMA FLOPs (F64)  │    0.00 │ 0.0 (0.0%)        │       0.00 │ Gflop  │  45260.80 │ 45260.8 (0.0%)  │          0.00 │ 0.0 (0.0%)     │
├─────────────┼───────────────────┼─────────┼───────────────────┼────────────┼────────┼───────────┼─────────────────┼───────────────┼────────────────┤
│ 11.1.6      │ MFMA IOPs (INT8)  │    0.00 │ 0.0 (0.0%)        │       0.00 │ Giop   │ 181043.20 │ 181043.2 (0.0%) │          0.00 │ 0.0 (0.0%)     │
╘═════════════╧═══════════════════╧═════════╧═══════════════════╧════════════╧════════╧═══════════╧═════════════════╧═══════════════╧════════════════╛
11.2 Pipeline Stats
...
```
I may need some extra help understanding where this issue is occuring

**Comment by ppanchad-amd** [comment] 2024-10-04 18:43
@JoseSantosAMD Issue is fixed. Closing ticket. Thanks!

**Closed by ppanchad-amd** 2024-10-04 18:43 UTC
Labels: bug
